services:
  - type: web
    name: inventory-backend
    env: python
    repo: https://github.com/yunussid/InventoryAndOrderMgmtSystem.git
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"

databases:
  - name: inventory-db
    plan: free
    databaseName: inventory_db
    user: postgres

